stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

test:
  stage: test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"

lint:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

deploy:
  stage: deploy
  only:
      - production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
