stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t ci-ec-auth .

lint:
  stage: test
  script:
    - docker run -l ci-ec-auth ci-ec-auth sh -c "npm run ci-lint"
    - docker container prune --filter label=ci-ec-auth -f
    - docker rmi ci-ec-auth
  needs: ["build"]

test:
  stage: test
  script:
    - docker run -l ci-ec-auth ci-ec-auth sh -c "npm run ci-test"
    - docker container prune --filter label=ci-ec-auth -f
    - docker rmi ci-ec-auth
  needs: ["build"]

deploy:
  stage: deploy
  only:
      - production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
