stages:
  - build
  - test
  - tempDeploy
  - deploy

variables:
  PROJECT: ci-ec-auth

# build:
#   stage: build
#   script:
#     - docker build -t $PROJECT .

# lint:
#   stage: test
#   script:
#     - docker run -l $PROJECT $PROJECT sh -c "npm run ci-lint"
#     - docker container prune --filter label=$PROJECT -f

# test:
#   stage: test
#   script:
#     - docker run -l $PROJECT $PROJECT sh -c "npm run ci-test"
#     - docker container prune --filter label=$PROJECT -f

# cleanup:
#   stage: test
#   script:
#     - docker rmi $PROJECT
#   needs: ["lint", "test"]


deployDatabase:
  stage: tempDeploy
  script:
    - microk8s kubectl apply -f mysql-pv.yaml
    - microk8s kubectl apply -f mysql-pvc.yaml
    - microk8s kubectl apply -f mysql-deployment.yaml
    # - microk8s kubectl apply -f persistence_volume.yaml
    - microk8s kubectl apply -f mysql-service.yaml
    # - microk8s kubectl apply -f mysql-ingress.yaml
    - microk8s kubectl apply -f node-deployment.yaml


deploy:
  stage: deploy
  only:
      - production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
