version: "3"
services:
  auth:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - auth_db
    command: npm run dev
    networks:
      - ecommerce
  auth_db:
    image: mariadb:10.7
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=auth_db
      - MARIADB_USER=joey
      - MARIADB_PASSWORD=root
    volumes:
      - auth_db:/var/lib/mysql
      - ./schema/001.sql:/docker-entrypoint-initdb.d/001.sql
  
volumes:
  auth_db:

networks:
  ecommerce:
    name: ecommerce
