version: "3"
services:
  ec_auth:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - ec_auth_db
    command: npm run dev
    networks:
      - ecommerce
      
  ec_auth_db:
    image: mariadb:10.7
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=ec_auth_db
      - MARIADB_USER=joey
      - MARIADB_PASSWORD=root
    volumes:
      - ec_auth_db:/var/lib/mysql
      - ./schema/002.sql:/docker-entrypoint-initdb.d/003.sql
    networks:
      - ecommerce
  
volumes:
  ec_auth_db:

networks:
  ecommerce:
    name: ecommerce
