apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: LoadBalancer
  ports:
  - name: mysql-service
    protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 30000
  selector:
    app: mysql
