apiVersion: v1
kind: PersistentVolume
metadata:
  name: ec-auth-mysql-pv
  labels:
    type: local
  finalizers: null
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
