apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysql-ingress
  namespace: mysql
spec:
  rules:
  - host: test.com
    http:
      paths:
      - backends:
          serviceName: mysql
          servicePort: 3306
