apiVersion: v1
kind: Service
metadata:
  name: ec-auth
spec:
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001
  type: LoadBalancer
  selector:
    app: ec-auth
