apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-volume
  namespace: mysql
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/mnt/data"
