apiVersion: v1
kind: Namespace
metadata:
  name: ec-auth-mysql
  labels:
    name: ec-auth-mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec-auth-mysql
spec:
  selector:
    matchLabels:
      app: ec-auth-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ec-auth-mysql
    spec:
      containers:
        - image: mysql:8.0
          name: ec-auth-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: ec_auth_db
            - name: MYSQL_USER
              value: joey
            - name: MYSQL_PASSWORD
              value: root
          ports:
            - containerPort: 3306
              name: ec-auth-mysql
          volumeMounts:
            - name: ec-auth-mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: ec-auth-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: ec-auth-mysql-pv-claim
